Django/escinema/cinema/cinema/urls.py
from django.contrib import admin
from django.urls import path , include
from django.contrib.auth import views as auth_views
from .views import *
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("home/",cinema_home,name="home"),
    path("",cinema_home,name="home"),
    path("registrati",UserCreate.as_view(),name="registrati"),
    path("login", auth_views.LoginView.as_view(), name="login"),
    path("logout",auth_views.LogoutView.as_view(template_name='home.html'),name="logout"),
    path("registrastaff",StaffCreate.as_view(),name="registrastaff "),
    path('gestione/',include('gestione.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/escinema/cinema/gestione/urls.py
from django.urls import path
from .views import *


app_name="gestione"

urlpatterns = [
    path('home/',listafilm,name="catalogo"),
    path('homesala/<int:id>',listasale,name="homesala"),
    path('creagiorno/',CreaGiornoView.as_view(),name="creagiorno"),
    path('storico/',situazionep,name="storico"),
    path('recensione/<int:id>',addRecensione, name="recensione"),
    path('vota/', vota, name="vota"),
    path('prenotazione/<int:id>',prenotazione,name="prenotazione"),
    path('modifica/<int:id>',cancella_p,name="modifica"),
    path('attesa/<int:id>',attesta_p,name="attesa"),
    path("inseriscifilm/", CreafilmView.as_view(), name="inseriscifilm"),
    path("inseriscisala/",CreaSalaView.as_view(),name="inseriscisala"),
    path("storicosala/",storicosala,name="storicosala"),
    path('rimuovi/<int:id>',rimuovisala,name="rimuovi"),
    path('storicofilm/', storicofilm, name="storicofilm"),
    path('rimuovifilm/<int:id>', rimuovifilm, name="rimuovifilm")

]

Django/escinema/cinema/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    {% block head %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
         <link rel="stylesheet" href="{% static 'stile.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>


     {% endblock %}
     {% load crispy_forms_tags %}
    </head>

    <title> {% block title %}{% endblock %}</title>
    <div class="jumbotron text-center">
        {% block header1 %}

          <h1>Header</h1>
          <p>Subtitle</p>
            <p>Stato_visitatore</p>
        {% endblock %}
        </div>

{% if user.is_authenticated and "ok" in request.GET.login  %}
<div id="info" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Welcome {{user.username}} </h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p> La procedura di login è andata a buon fine </p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-info" data-dismiss="modal">Chiudi</button>
        </div>
      </div>
    </div>
  </div> 
  <script>
    $(document).ready(function(){
        $("#info").modal('show');});
        function logout(){
            alert("Hai effettuato il logout arrivederci!")
        }
  </script>
  
  
{% endif %}
    <center>
        {% block content1 %}
            <a></a>
        {% endblock %}
        {% block content %}

        {% endblock %}
    </center>
</html>

Django/escinema/cinema/templates/create_user.html
{% extends 'base.html' %}

{% load static %}

{% load crispy_forms_tags %} 
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> 
<link rel="stylesheet" href="{% static 'stile.css' %}">
{% block title %} Creazione Utente {{ form.user_group_name }} {% endblock %} 

{% block header1 %}
  <h1>Pagina di Registrazione</h1>
  <p>Si prega di compilare i campi necessari</p> 
{% endblock %}

{% block content1 %}
<div>
<form method="post"> {% csrf_token %}

  {{form | crispy}}
  
  <input type="submit" class="btn btn-success" value="Registrati ora!">
  
  </form>
</div>
{% endblock %}

{% block footer %} {% endblock %}

Django/escinema/cinema/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
     <link rel="stylesheet" href="{% static 'stile.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script>
    {% for a in listaattesa %}
            {% if user.id == a.user_id and a.sala.posti >= a.posti_richiesti %}
                confirm("si sono liberati dei posti per lo spettacolo {{ a.sala.film.titolo }}")
            {% endif %}
    {% endfor %}
</script>
    {% endblock %}
{% block title %}  Home del Cinema {% endblock %}

{% block header1 %}
    <h1>Home del Cinema</h1>
    <p>Homepage del nostro cinema </p>
    {%  if user.is_authenticated  %}
    <p>Benvenuto {{ user.username }}</p>
        {% elif user.is_ %}
        <p>Benvenuto guest</p>
    {% endif %}
    {% for message in messages %}
        <p style="text-align:center;">{{message}}</p>
    {% endfor %}
{% endblock  %}

{% block content %}
    <nav class="menu">
{%  if  user.is_staff or staff  %}
    <ul>
     <li class="menu-list"><a  onclick="Check()" href= "{% url 'gestione:storico' %}" role="banner">Storico Prenotazioni</a></li> |
    <li class="menu-list"><a onclick="Check()" href= "{% url 'gestione:vota' %}" role="banner">Vota Spettacolo</a></li> |
        <li class="menu-list"><a onclick="Check()" href= "{% url 'gestione:inseriscisala' %}" role="banner">Aggiungi Spettacolo</a></li> |
            <li class="menu-list"><a onclick="Check()" href= "{% url 'gestione:storicosala' %}" role="banner">Rimuovi Spettacolo</a></li> |
                <li class="menu-list"><a onclick="Check()" href= "{% url 'gestione:storicofilm' %}" role="banner">Rimuovi Film</a></li>


    </ul>
        {% elif user.is_authenticated %}
            <ul>
                <li class="menu-list"><a  onclick="Check()" href= "{% url 'gestione:storico' %}" role="banner">Storico Prenotazioni</a></li> |
                <li class="menu-list"><a onclick="Check()" href= "{% url 'gestione:vota' %}" role="banner">Vota Spettacolo</a></li>
            </ul>
        {% else %}
        <a>Utente non loggato</a>

    {% endif %}
    </nav>
            <a class="btn btn-info" href="{% url 'registrati' %}" role="button">Registrati</a>
            <a class="btn btn-info"  href="{%  url 'login' %}" role="button">Login</a>
            <a class="btn btn-info" href="/gestione/home/" role="button">Catalogo</a>
    {%  if user.is_authenticated  %}
      <a class="btn btn-info" onclick="logout()" href= "{% url 'logout' %}" role="button" >Logout</a>
    {% else %}
        <a class="btn btn-info" onclick="cbCheck()"   disabled="disabled">Logout</a>
    {% endif %}

{% endblock %}

<script type="text/javascript">
    function cbCheck(){
                        alert("accesso non consentito")
    }
</script>