tirocinio/Django/ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path , include
from django.contrib.auth import views as auth_views
from .views import *
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('prodotti/',include('prodotti.urls')),
    path("home/",ecommerce_home,name='home'),
    path("registrazione/",UserCreate.as_view(),name="registrazione"),
    path("login/",auth_views.LoginView.as_view(),name='login'),
    path("logout/",auth_views.LogoutView.as_view(),name='logout'),
    path("aboutus/",AboutUs,name='chisiamo'),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tirocinio/Django/ecommerce/prodotti/urls.py
from django.urls import path
from .views import *

app_name="prodotti"

urlpatterns = [
    path('catalogo/',listaprodotti,name='catalogo'),
    path('carrello/<int:id>',agg_carrello,name='carrello'),
    path('prenotazione/',prenotazione,name='prenotazione'),
    path('acquisto/',acquisto,name='acquisto'),
    path('storico/',storico,name='storico'),
    path('valutazione/<int:id>',recensione,name='recensione'),
    path('modifica/<int:id>',modificaOrdine,name='modifica'),
    path('cancella/<int:id>',cancellaOrdine,name='cancella'),
]

tirocinio/Django/ecommerce/templates/about.html
{% extends 'base2.html' %}
{% load static %}
{% block content %}
    <div class="headerimg">
        <img src="{% static 'imgs/provablumen.jpg' %}">
    </div>
    <br>
    <h1 align="left">Chi siamo</h1>
    <br><br>
    <h2 align="left">Le origini del gruppo</h2>
    <p align="left">
        Le origini del Blumen Group risalgono agli anni ’20, quando il suo fondatore mosse i primi passi in un mercato ancora unbranded. Da allora molta strada è stata fatta
        ed oggi Blumen Group, dopo anni e anni di esperienza, può fregiarsi del titolo di protagonista nel mercato delle sementi per l’orto ed il giardino, sia nel settore<br>
        hobbistico sia in quello professionale.
    </p>
    <br><br>
    <h3 align="left">Le origini del gruppo</h3>
    <br>
    <h2 align= "left"> Dalla ricerca alla qualità dei prodotti</h2>
    <p align="left">
        Ricerca, innovazione, servizio e qualità dei prodotti sono gli elementi distintivi del successo del Gruppo, che dalle sementi ha allargato la sua esperienza anche al mercato dei concimi, 
        dove ha saputo in breve tempo ritagliarsi un ruolo da protagonista.
        Gli ultimi 20 anni sono stati determinanti nella crescita del Gruppo, che oggi rappresenta un esempio di polo di aggregazione di piccole e medie aziende del settore, riconosciute come eccellenze italiane.
         Questo processo di crescita è stato accompagnato da importanti investimenti in R&S, finalizzata all’ottenimento di varietà orticole che si distinguono non solo per le qualità estetiche ma soprattutto per le caratteristiche di “sapore”.
    </p>

{% endblock content %}

tirocinio/Django/ecommerce/templates/base2.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    {% load crispy_forms_tags %}
    

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style2.css' %}">
    <head>
            <meta charset="UTF-8">
            <title> Tobi store| Ecommerce Agrario </title>
             <link rel="preconnect" href="https://fonts.googleapis.com">
            <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
            <link href="https://fonts.googleapis.com/css2?family=Abyssinica+SIL&display=swap" rel="stylesheet"> 
    </head>
    <body>
        <div class="header">
            
        <div class="container">
            <div class="navbar">
                <div class="logo"><br>
                    <img src="{% static "imgs/four-logo.png" %}" width="125px">
                    <h1>Tobi Store </h1>
                </div>
                {% if user.is_authenticated %}
                <nav>
                    <ul>
                        <li><a href="{% url 'home' %}">Home</a></li>
                        <li><a href="{% url 'prodotti:catalogo' %}">Product</a></li>
                        <li><a href="{% url 'prodotti:storico' %}">Storico</a></li>
                        <li><a href="{% url 'chisiamo' %}">About</a></li>
                        <li><a href="{% url 'logout' %}">Logout</a></li>
                        {% if user.is_superuser == 1 %}
                        <li><a href="http://127.0.0.1:8000/admin/">Pannello admin</a></li>
                        <li><a href="">Aggiungi Prodotto</a></li>
                        {% endif %}
                        <li><button onclick=Funzione()><img src={% static "imgs/carrello-pieno.png" %} width="30px" height="30px"></button></li>
                    </ul>
                </nav>
                {% else %}
                <nav>
                    <ul>
                        <li><a href="{% url 'home' %}">Home</a></li>
                        <li><a href="{% url 'prodotti:catalogo' %}">Product</a></li>
                        <li><a href="{% url 'chisiamo' %}">About</a></li>
                        <li><a href="{% url 'login' %}">Accedi</a></li>
                        <li><a href="{% url 'registrazione' %}">Registrati</a></li>
                        <li><button onclick=Funzione()><img src={% static "imgs/carrello-vuoto.png" %} width="30px" height="30px"></button></li>
                    </ul>
                </nav>
                {% endif %}
                
                <script>
                    function Funzione(){
                        window.location.replace('http://127.0.0.1:8000/prodotti/prenotazione/')
                    }
                </script>
            </div>

            {% block content %}

            {% endblock %}

        </div>
        <!--footer-->
    <div class='footer'>
        <div class="container">
            <div class="row">
                <div class="f-col-1">
                    <h3> Downloads our app</h3>
                    <p>Download le app per android e per ios mobile </p>
                    <div class="app-logo">
                        <img src="{% static "imgs/ps-logo.jpg" %}">
                        <img src="{% static "imgs/as-logo.png" %}">
                    </div>
                </div>
                <div class="f-col-2">
                    <center>
                        <img src="{% static "imgs/four-logo.png" %}">
                        <p>Sempre alla ricerca di nuovi benefits per voi </p></center>
                   
                </div>
                <div class="f-col-3">
                    <h3> Link utili</h3>
                    <ul>
                        <li><a href="https://vargiuweb.it" style="color:#FFF">Coupons</a></li>
                        <li><a href="https://vargiuweb.it" style="color:#FFF">policy</a></li>
                        <li><a href="https://vargiuweb.it" style="color:#FFF">Join Affiliate</a></li>
                    </ul>
                    
                </div>
                <div class="f-col-4">
                    <h3> Seguici anche </h3>
                    <ul>
                        <li><a href="https://it-it.facebook.com/pagina.diprova.5/" style="color:#FFF">Facebook</a></li>
                        <li><a href="https://twitter.com" style="color:#FFF">Twitter</a></li>
                        <li><a href="https://www.instagram.com/piante.it/" style="color:#FFF">instagram</a></li>
                    </ul>
                </div>
                </div>
                <hr>
                <p class="copyright">Copyright 2022 -  Danilo Bellocchio </p>

            </div>

</body>
</html>

tirocinio/Django/ecommerce/templates/create_user.html
{% extends 'base2.html' %}
{% load static %}
{% load crispy_forms_tags %}  
{% block content %}
            <h2>Pagina di Registrazione</h2>
            <p>Si prega di compilare i campi necessari</p> 
            <div>
              <form method="post"> {% csrf_token %}
              {{form | crispy}}
              <input type="submit" class="btn btn-success" value="Registrati ora!">
            </form>
            </div>
{% endblock content %}

tirocinio/Django/ecommerce/templates/home.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    {% load crispy_forms_tags %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <head>
    <link rel="stylesheet" href="{% static 'style.css' %}">

            <meta charset="UTF-8">
            <title> Tobi store| Ecommerce Agrario </title>
             <link rel="preconnect" href="https://fonts.googleapis.com">
            <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
            <link href="https://fonts.googleapis.com/css2?family=Abyssinica+SIL&display=swap" rel="stylesheet"> 
    </head>
    <body>
        <div class="header">
        <div class="container">
            {% for message in messages %}
            <p style="text-align:center;">{{message}}</p>
            {% endfor %} 
            <div class="navbar">
                <div class="logo">
                    <img src="{% static "imgs/four-logo.png" %}" width="125px">
                </div>
                {% if user.is_authenticated %}
                <nav>
                    <ul>
                        <li><a href="{% url 'home' %}">Home</a></li>
                        <li><a href="{% url 'prodotti:catalogo' %}">Product</a></li>
                        <li><a href="{% url 'prodotti:storico' %}">Storico</a></li>
                        <li><a href="{% url 'chisiamo' %}">About</a></li>
                        <li><a href="{% url 'logout' %}">Logout</a></li>
                        {% if user.is_superuser == 1 %}
                        <li><a href="http://127.0.0.1:8000/admin/">Pannello admin</a></li>
                        <li><a href="">Aggiungi Prodotto</a></li>
                        {% endif %}
                    </ul>
                </nav>
                {% else %}
                <nav>
                    <ul>
                        <li><a href="{% url 'home' %}">Home</a></li>
                        <li><a href="{% url 'prodotti:catalogo' %}">Product</a></li>
                        <li><a href="{% url 'chisiamo' %}">About</a></li>
                        <li><a href="{% url 'login' %}">Accedi</a></li>
                        <li><a href="{% url 'registrazione' %}">Registrati</a></li>
                    </ul>
                </nav>
                {% endif %}
                    <button onclick=Funzione()><img src={% static "imgs/carrello-vuoto.png" %} width="30px" height="30px"></button>
                <script>
                    function Funzione(){
                        window.location.replace('http://127.0.0.1:8000/prodotti/prenotazione/')
                    }
                </script>
            </div>
            <div class="row">
                <div class="col-2">
                    <h1>Tobi Store</h1>
                    {% if user.is_authenticated %}
                        <h3> Benvenuto {{user.username}}</h3>
                    <p>
                        <br>In una terra lontana, dietro le montagne Parole, lontani dalle terre di Vocalia e Consonantia, vivono i testi casuali.<br> Vivono isolati nella cittadina di Lettere, sulle coste del Semantico, un immenso oceano linguistico.<br>
                    </p>
                    {% else %}
                    <h3> Sei autenticato come ospite</h3>
                    <p>
                        <br>In una terra lontana, dietro le montagne Parole, lontani dalle terre di Vocalia e Consonantia, vivono i testi casuali. <br>Vivono isolati nella cittadina di Lettere, sulle coste del Semantico, un immenso oceano linguistico.<br>
                    </p>
                    {% endif %}
                    
                    <a href="{% url 'prodotti:catalogo' %}" class="btn">Vai al catalogo &#8594</a>
                </div>
                <div class="col-2">
                    <img src={% static "imgs/sementi2.png" %}
                </div>
            </div>
        </div>
    </div>
</div>
    <div class="categories">
        <div class="small-container">
            <h2 class="title1"> Categories </h2>
            <div class="row">
                <div class="col-3">
                    <img src={% static "imgs/frutta-verdura.png" %}>
                    <h4>Frutta e verdura</h4>
                </div>
                <div class="col-3">
                    <img src={% static "imgs/fiori.png" %}>
                    <h4>Bulbi da fiore</h4>
                </div>
                <div class="col-3">
                    <img src={% static "imgs/animali.png" %}>
                    <h4>Prodotti per animali</h4>
                </div>
            </div>
        </div>
    </div>

    <!--footer-->
    <div class='footer'>
        <div class="container">
            <div class="row">
                <div class="f-col-1">
                    <h3> Downloads our app</h3>
                    <p>Download le app per android e per ios mobile </p>
                    <div class="app-logo">
                        <img src="{% static "imgs/ps-logo.jpg" %}">
                        <img src="{% static "imgs/as-logo.png" %}">
                    </div>
                </div>
                <div class="f-col-2">
                    <img src="{% static "imgs/four-logo.png" %}">
                    <p>Sempre alla ricerca di nuovi benefits per voi </p>
                   
                </div>
                <div class="f-col-3">
                    <h3> Link utili</h3>
                    <ul>
                        <li><a href="https://vargiuweb.it" style="color:#FFF">Coupons</a></li>
                        <li><a href="https://vargiuweb.it" style="color:#FFF">policy</a></li>
                        <li><a href="https://vargiuweb.it" style="color:#FFF">Join Affiliate</a></li>
                    </ul>
                    
                </div>
                <div class="f-col-4">
                    <h3> Seguici anche </h3>
                    <ul>
                        <li><a href="https://it-it.facebook.com/pagina.diprova.5/" style="color:#FFF">Facebook</a></li>
                        <li><a href="https://twitter.com" style="color:#FFF">Twitter</a></li>
                        <li><a href="https://www.instagram.com/piante.it/" style="color:#FFF">instagram</a></li>
                    </ul>
                </div>
                </div>
                <hr>
                <p class="copyright">Copyright 2022 -  Danilo Bellocchio </p>
        </div>
    </div>
</body>
</html>