Django/escinema/cinema/cinema/urls.py
from django.contrib import admin
from django.urls import path , include
from django.contrib.auth import views as auth_views
from .views import *
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("home/",cinema_home,name="home"),
    path("",cinema_home,name="home"),
    path("registrati",UserCreate.as_view(),name="registrati"),
    path("login", auth_views.LoginView.as_view(), name="login"),
    path("logout",auth_views.LogoutView.as_view(template_name='home.html'),name="logout"),
    path("registrastaff",StaffCreate.as_view(),name="registrastaff "),
    path('gestione/',include('gestione.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/escinema/cinema/gestione/urls.py
from django.urls import path
from .views import *


app_name="gestione"

urlpatterns = [
    path('home/',listafilm,name="catalogo"),
    path('homesala/<int:id>',listasale,name="homesala"),
    path('creagiorno/',CreaGiornoView.as_view(),name="creagiorno"),
    path('storico/',situazionep,name="storico"),
    path('recensione/<int:id>',addRecensione, name="recensione"),
    path('vota/', vota, name="vota"),
    path('prenotazione/<int:id>',prenotazione,name="prenotazione"),
    path('modifica/<int:id>',cancella_p,name="modifica"),
    path('attesa/<int:id>',attesta_p,name="attesa"),
    path("inseriscifilm/", CreafilmView.as_view(), name="inseriscifilm"),
    path("inseriscisala/",CreaSalaView.as_view(),name="inseriscisala"),
    path("storicosala/",storicosala,name="storicosala"),
    path('rimuovi/<int:id>',rimuovisala,name="rimuovi"),
    path('storicofilm/', storicofilm, name="storicofilm"),
    path('rimuovifilm/<int:id>', rimuovifilm, name="rimuovifilm")

]

Django/escinema/cinema/gestione/models.py
from django.contrib.auth.models import User
from django.forms import *
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.


class Giorno(models.Model):
    giorno = models.DateField()
    orario = models.TimeField()

    class Meta:
        verbose_name_plural = "Giorni"

    def __str__(self):
        return str(self.giorno) + " alle " + str(self.orario) 

class Film(models.Model):
    titolo = models.CharField(max_length=50)
    immagine = models.ImageField()
    regista = models.CharField(max_length=50)
    attore = models.CharField(max_length=50)
    sinossi = models.CharField(max_length=300)
    categoria = models.CharField(max_length=30)
    durata  = models.CharField(max_length=10)
    media_valutazione = models.FloatField(default=0,validators=[MaxValueValidator(10),MinValueValidator(0)])

    class Meta:
        verbose_name_plural="Film"
    
    def __str__(self):
        return self.titolo

class Sala(models.Model):
    s_immagine = models.ImageField(default=None)
    tipo = models.CharField(max_length=20)
    posti = models.IntegerField(default=20)
    giorno = models.OneToOneField(Giorno,on_delete=models.CASCADE,default="")
    film = models.ForeignKey(Film,on_delete=models.CASCADE,default="")

    class Meta:
        verbose_name_plural = "Sale"

    def __str__(self):
        return str(self.film) + " " + self.tipo + " " + str(self.giorno)


class Prenotazione(models.Model):
    user = models.ForeignKey(User,on_delete=models.PROTECT,default=None)
    sala = models.ForeignKey(Sala,on_delete=models.CASCADE,default="")
    n_posti = models.IntegerField(default=1,validators=[MaxValueValidator(20),MinValueValidator(1)])

    class Meta:
        verbose_name_plural = "Prenotazioni"

    def __str__(self):
        return "Prenotazione a nome " + str(self.user) + " per " + str(self.sala)

class Recensioni(models.Model):
    id = models.AutoField(primary_key=True)
    film = models.ForeignKey(Film, on_delete=models.CASCADE, default="")
    user = models.ForeignKey(User, on_delete=models.CASCADE, default="")
    recensione = models.CharField(max_length=300)
    stelle = models.FloatField(default=0, validators=[MaxValueValidator(10), MinValueValidator(1)])

    class Meta:
        verbose_name_plural = "Recensioni"

    def __str__(self):
        return str(self.film) + " voto: " + str(self.stelle)

class Attesa(models.Model):
    user = models.ForeignKey(User,on_delete=models.PROTECT,default=None)
    sala = models.ForeignKey(Sala,on_delete=models.CASCADE,default="")
    posti_richiesti = models.IntegerField(default=1,validators=[MaxValueValidator(20),MinValueValidator(1)])

    class Meta:
        verbose_name_plural = "Attesa"

    def __str__(self):
        return "Attesa posti liberi per" + str(self.user) + ": " + str(self.sala)

Django/escinema/cinema/gestione/forms.py
import datetime
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django.forms.widgets import *
from .models import *
from django.forms import ModelForm
from bootstrap_datepicker_plus.widgets import DatePickerInput

class SalaForm(ModelForm):
    helper = FormHelper()
    helper.form_id = "addfilm_crispy_form"
    helper.form_method = "POST"
    helper.add_input(Submit("submit", "Aggiungi film a Sala"))

    class Meta:
        model = Sala
        fields = ("tipo","s_immagine","posti","giorno","film")

class GiornoForm(ModelForm):
    helper = FormHelper()
    helper.form_id = "addorario_crispy_form"
    helper.form_method = "POST"
    helper.add_input(Submit("submit", "Aggiungi Giorno e orario"))

    class Meta:
        model = Giorno
        fields = ("giorno", "orario")
        widgets = {
            'giorno' : DatePickerInput (
                options={
                    'minDate' :(datetime.datetime.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d '),
                    'maxDate': (datetime.datetime.today() + datetime.timedelta(days=15)).strftime('%Y-%m-%d ')
                }
            )
        }


class CreafilmForm(ModelForm):
    helper = FormHelper()
    helper.form_id = "addfilm_crispy_form"
    helper.form_method = "POST"
    helper.add_input(Submit("submit", "Aggiungi Film"))

    class Meta:
        model = Film
        fields = ("titolo", "immagine", "regista", "attore", "sinossi", "durata", "categoria")


class RecensioniForm(ModelForm):
    helper = FormHelper()
    helper.form_show_labels = False

    class Meta:
        model = Recensioni
        fields = ['recensione', 'stelle']


class PrenForm(ModelForm):
    helper = FormHelper()
    helper.form_show_labels = False
    helper.add_input(Submit("submit", "Prenotati"))

    class Meta:
        model = Prenotazione
        fields = ['n_posti']


class AttesaForm(ModelForm):
    helper = FormHelper()
    helper.form_show_labels = False
    helper.add_input(Submit("submit", "Mettiti in attesa"))

    class Meta:
        model = Attesa
        fields = ['posti_richiesti']

Django/escinema/cinema/gestione/views.py
from django.contrib import messages
from .models import *
from .forms import *
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.contrib.auth.decorators import login_required
from braces.views import GroupRequiredMixin
from .models import *


def listafilm(request):

    listaidfilmprenotati = []  # lista film prenotati
    listaprenotazioni = []  # lista id user che hanno fatto prenotazioni
    listacategoriafilmprenotati = []  # lista dei generi dei film da cercare
    listaregisti = []  # lista registi dei film prenotati già
    listaattori = []  # lista attori dei film prenotati
    listaspettacoli = []  # lista contenente tutti gli spettacoli del cinema

    film_cons_attori=[] #film consigliati per attore
    film_cons_genere=[] #film consigliati per categoria
    film_cons_regista=[] #film consigliati per registi

    spettacoli = Sala.objects.all()
    listafilm = Film.objects.order_by('-media_valutazione')
    pren = Prenotazione.objects.all()

    if request.user.is_authenticated:
        user = User.objects.get(pk=request.user.id)
        for s in spettacoli:
            listaspettacoli.append(s.film_id)

        for p in pren:
            if user.id == p.user_id:
                listaidfilmprenotati.append(p.sala.film_id)

                listaprenotazioni.append(p.user_id)

                listacategoriafilmprenotati.append(p.sala.film.categoria)

                listaregisti.append(p.sala.film.regista)

                listaattori.append(p.sala.film.attore)

        for l in listafilm:
            if (l.categoria in listacategoriafilmprenotati and l.id not in listaidfilmprenotati and l.id in listaspettacoli):
                film_cons_genere.append(l)
            if (l.regista in listaregisti and l.id not in listaidfilmprenotati and l.id in listaspettacoli):
                film_cons_regista.append(l)
            if (l.attore in listaattori and l.id not in listaidfilmprenotati and l.id in listaspettacoli):
                film_cons_attori.append(l)

        ctx= {'listafilm': listafilm, 'listapren': listaprenotazioni, 'listafilmprenotati': listaidfilmprenotati,
                   'listaspettacoli': listaspettacoli, 'listagenere': listacategoriafilmprenotati,
                   'listaregisti': listaregisti, 'listaattori': listaattori,'cons_regista':film_cons_regista,'cons_attore':film_cons_attori,'cons_genere':film_cons_genere}
    else:
        ctx={"listafilm":listafilm}

    return render(request, 'gestione/home.html',ctx)



def listasale(request, id):
    listasale = Sala.objects.order_by('posti')
    return render(request, 'gestione/homesala.html', {'listasale': listasale})

@login_required
def situazionep(request):
    user = get_object_or_404(User, pk=request.user.pk)
    # qui ho creato una lista dove vengono inserite le prenotazioni di ogni user

    storico = []
    # quando provi ad entrare questo ciclo inserisce tutte le tue prenotazioni in pren che poi verrà usato dall'html in seguito

    for p in Prenotazione.objects.all():
        # controllo se quell'user ha effettuato prenotazioni
        if user.id == p.user_id:

            for s in Sala.objects.all():
                if s.id == p.sala_id:
                    # aggiungo prenotazione alla lista
                    storico.append(p)
    ctx = {'listafilm': storico}
    return render(request, "gestione/storico.html", ctx)


@login_required
def addRecensione(request, id):
    form = RecensioniForm()
    fi = Film.objects.get(pk=id)
    user = User.objects.get(pk=request.user.id)

    if request.method == 'POST':
        form = RecensioniForm(request.POST)
        if form.is_valid():
            c = form.save(commit=False)
            c.film = fi
            c.user = user
            c.save()
            s_recensioni = Recensioni.objects.filter(film=fi)
            somma = fi.media_valutazione + c.stelle
            if (len(s_recensioni) <= 2):
                fi.media_valutazione = somma / len(s_recensioni)
            else:
                fi.media_valutazione = somma / 2
            fi.media_valutazione = round(fi.media_valutazione, 1)
            fi.save()

            messages.success(request,"recensione avvenuta correttamente")
            return redirect('home')
    return render(request, 'gestione/recensioni.html', {"form": form})


def vota(request):
    user = get_object_or_404(User, pk=request.user.pk)
    pren = []
    for p in Prenotazione.objects.all():
        if user.id == p.user_id:
            for s in Sala.objects.all():
                if s.id == p.sala_id:
                    pren.append(s)
    ctx = {'listafilm': pren}
    return render(request, "gestione/vota.html", ctx)





def prenotazione(request, id):
    form = PrenForm()
    sala = Sala.objects.get(id=id)
    att = Attesa.objects.all()
    if request.method == 'POST':
        form = PrenForm(request.POST)
        sala = Sala.objects.get(pk=id)
        us_pren = User.objects.get(pk=request.user.id)
        for t in att:
            if (t.user_id == us_pren.id) and (t.sala_id == sala.id):
                r = Attesa.objects.get(pk=t.id)
                r.delete()
        if form.is_valid():
            c = form.save(commit=False)
            if c.n_posti > sala.posti:
                messages.info(request, "posti non disponibili")
            else:
                c.user = us_pren
                c.sala = sala
                sala.posti -= c.n_posti
                sala.save()
                c.save()
                messages.success(request,"prenotazione avvenuta con successo")
                return redirect('gestione:catalogo')
    return render(request, "gestione/pren.html", {"sala": sala, "form": form, "film": listafilm})


@login_required
def cancella_p(request, id):
    pren = Prenotazione.objects.get(pk=id)
    nposti = pren.n_posti
    sa = pren.sala_id
    pren.delete()
    s = Sala.objects.get(pk=sa)
    s.posti += nposti
    s.save()
    messages.success(request,"cancellazione prenotazione con successo")
    return redirect("http://127.0.0.1:8000/gestione/home/")


def attesta_p(request, id):
    form = AttesaForm()
    sala = Sala.objects.get(id=id)
    if request.method == 'POST':
        form = AttesaForm(request.POST)
        sala = Sala.objects.get(pk=id)
        us_pren = User.objects.get(pk=request.user.id)
        if form.is_valid():
            c = form.save(commit=False)
            c.user = us_pren
            c.sala = sala
            c.save()
            messages.success(request,"inserimento in lista avvenuto correttamente")
            return redirect('gestione:catalogo')
    return render(request, "gestione/pren.html", {"sala": sala, "form": form})

#sezione creazione spettacolo

class CreafilmView(GroupRequiredMixin, CreateView):
    group_required = ["staff"]
    title = "Aggiungi film al catalogo"
    form_class = CreafilmForm
    template_name = "gestione/crea_film.html"
    success_url = reverse_lazy("gestione:inseriscisala")

    def form_valid(self, form):
      messages.success(self.request, "film creato")
      return super().form_valid(form)

class CreaGiornoView(GroupRequiredMixin, CreateView):
    group_required = ["staff"]
    title = "Aggiunta di un orario settimanale"
    form_class = GiornoForm
    template_name = "gestione/crea_ora.html"
    success_url = reverse_lazy("gestione:inseriscisala")

    def form_valid(self, form):
      messages.success(self.request, "giorno creato")
      return super().form_valid(form)



class CreaSalaView(GroupRequiredMixin, CreateView):
    group_required = ["staff"]
    title = "Aggiungi Sala"
    form_class = SalaForm
    template_name = "gestione/crea_sala.html"
    success_url =  reverse_lazy("home")

@login_required
def storicosala(request):
    s = Sala.objects.all()
    return render(request, 'gestione/storico_sala.html', {'listasale': s})

@login_required
def rimuovisala(request,id):
    pren = Sala.objects.get(pk=id)
    pren.delete()
    messages.success(request,"sala rimossa correttamente")
    return redirect('home')

def storicofilm(request):
    f = Film.objects.all()
    return render(request,'gestione/cancellazione_film.html',{'listafilm' : f})

@login_required
def rimuovifilm(request,id):
    fi = Film.objects.get(pk=id)
    fi.delete()
    messages.success(request,"film rimosso correttamente")
    return redirect('home')

Django/escinema/cinema/gestione/templates/gestione/attesa.html
{% extends 'base.html' %}

{% block title %} {{view.title}} {% endblock  %}

{% load crispy_forms_tags %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> 

{% block header1 %}
    <h1> {{view.title}}</h1>
{% endblock  %}

{% block content %}

    <br>
    <div class="d-flex justify-content-center">
        {% crispy form %}
    </div>
    <br>
    
{% endblock  %}

Django/escinema/cinema/gestione/templates/gestione/cancellazione_film.html
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'stile01.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
{% endblock %}
{% block header1 %}
    <div>
    <center>
        <h1>Storico Film Cinema</h1>
    <p>Film presenti al cinema </p>
        {%  if user.is_authenticated  %}
    <a class="btn" href="{% url "home" %}" role="button">Home</a><br>
        {% else %}
         <a class="btn" href="{% url "home" %}" role="button">Home</a>
        <a class="btn"  href="{%  url 'login' %}" role="button">Login</a>
    {% endif %}
    </center>
    </div>
{% endblock  %}


{% block content1 %}
   <p align='justify'>

    {% for l in listafilm %}

        <ul>
        <div1 style="float: left" >

        <img src='{{ l.immagine.url }}' align='left' height="220" width="200" class="imageborder" /><br>
            <h3><font color="#d2691e"> {{ l }} </font><br></h3>
            <a>Regista: {{ l.regista }}<br></a>
            <a>Durata: {{ l.durata }}<br></a>
            <a>Attore: {{ l.attore }}<br></a>
            <a>Categoria: {{ l.categoria }}<br></a>
            <a>Valutazione: {{ l.media_valutazione }}<br></a>
            <a>Trama: {{ l.sinossi }}<br><br></a>


                             <a class="button-62"  onclick="motiva()" href="http://127.0.0.1:8000/gestione/rimuovifilm/{{ l.id }}" role="button">Cancella</a><br>
                             <hr color="black" align=”left” size=”1″ width=”300″  noshade>

        </ul>
        </div1>
    {% endfor %}
    </body>
        <script>
        function motiva(){
            alert("attenzione!! la cancellazione di un film comporta la rimozione delle prenotazioni e delle sale ad esso collegate.")
        }
        </script>
{% endblock %}

Django/escinema/cinema/gestione/templates/gestione/crea_film.html
{% extends 'base.html' %}

{% block title %} {{view.title}} {% endblock  %}

{% load crispy_forms_tags %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

{% block header1 %}
    <h1> {{view.title}}</h1>
{% endblock  %}

{% block content %}

    <br>
    <div class="d-flex justify-content-center">
        {% crispy form %}
    </div>
    <br>

{% endblock  %}

Django/escinema/cinema/gestione/templates/gestione/crea_ora.html
{% extends 'base.html' %}

{% block title %} {{view.title}} {% endblock  %}

{% load crispy_forms_tags %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> 

{% block header1 %}
    <h1> {{view.title}}</h1>
{% endblock  %}

{% block content %}

    <br>
    <div class="d-flex justify-content-center">
        {% crispy form %}
    </div>
    <br>
    
{% endblock  %}

Django/escinema/cinema/gestione/templates/gestione/crea_sala.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
     <link rel="stylesheet" href="{% static 'stile.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
{% endblock %}

{% block title %} {{view.title}} {% endblock  %}

{% load crispy_forms_tags %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

{% block header1 %}
    <h1> {{view.title}}</h1>
<a class="btn" href="{% url "home" %}" role="button">Home</a>
{% for message in messages %}
        <p style="text-align:center;">{{message}}</p>
    {% endfor %}
{% endblock  %}

{% block content %}
    <nav class="menu">
<ul>
     <li class="menu-list"><a href= "{% url 'gestione:inseriscifilm' %}" role="banner">Aggiungi film</a></li> |
          <li class="menu-list"><a href= "{% url 'gestione:creagiorno' %}" role="banner">Aggiungi Data Spettacolo</a></li>
</ul>
        </nav>
    <br>
    <div class="d-flex justify-content-center">
        {% crispy form %}
    <br>
    </div>


    <br>
{% endblock  %}

Django/escinema/cinema/gestione/templates/gestione/home.html
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'stile01.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
{% endblock %}
{% block header1 %}
    <div>
    <center>
        <h1>Catalogo del Cinema</h1>
    <p>Catalogo del nostro cinema </p>
        {%  if user.is_authenticated  %}
    <a class="btn" href="{% url "home" %}" role="button">Home</a><br>
        {% else %}
         <a class="btn" href="{% url "home" %}" role="button">Home</a>
        <a class="btn"  href="{%  url 'login' %}" role="button">Login</a>
    {% endif %}
    </center>
        <a><b><font color="#d2691e">Trova il tuo spettacolo con un click:</font></b></a>
     <select name=”film” size=”1″  onchange="Controlla(this.value)">
    <option disabled selected="selected">Cerca film</option>
    {% for l in listafilm %}
        {%  if l.id in listaspettacoli %}
            <option value={{ l.id }}>{{ l.titolo }}</option>
        {% endif %}
    {% endfor %}
     </select>
     {% for message in messages %}
        <p style="text-align:center;">{{message}}</p>
    {% endfor %}
    </div>
    <br>
{% endblock  %}

{% block content %}
        {%  if user.is_authenticated  %}
    <ul>
   <div1 style="float: left" >


    {%  if cons_genere %}
    <h5 align="left"><font color="#d2691e"> Film consigliati per genere:</font></h5>
{% for f in cons_genere %}

<a href="http://127.0.0.1:8000/gestione/homesala/{{ f.id }}"><img src='{{ f.immagine.url }}'  height="120" width="100" class="imageborder"/></a>

{% endfor %}
<hr color="black" align=”left” size=”1″ width=”300″  noshade>
{% endif %}



{% if  cons_regista %}
    <h5 align="left"><font color="#d2691e">Film consigliati per regista:</font></h5>
{% for f in cons_regista %}
<a href="http://127.0.0.1:8000/gestione/homesala/{{ f.id }}"><img src='{{ f.immagine.url }}'  height="120" width="100" class="imageborder"/></a>
{% endfor %}
                                       <hr color="black" align=”left” size=”1″ width=”300″  noshade>
{% endif %}


{%  if cons_attore  %}
<h5 align="left"><font color="#d2691e">Film consigliati per attore principale:</font></h5>
{% for f in cons_attore %}
<a href="http://127.0.0.1:8000/gestione/homesala/{{ f.id }}"><img src='{{ f.immagine.url }}'  height="120" width="100" class="imageborder"/></a>
{% endfor %}
                 <hr color="black" align=”left” size=”1″ width=”300″  noshade>
{% endif %}
                <br>
    </div1>
    </ul>
    {% endif %}
{% endblock %}

{% block content1 %}
   <p align='justify'>

    {% for l in listafilm %}

        <ul>
        <div1 style="float: left" >

        <img src='{{ l.immagine.url }}' align='left' height="220" width="200" class="imageborder" /><br>
            <h3><font color="#d2691e"> {{ l }} </font><br></h3>
            <a>Regista: {{ l.regista }}<br></a>
            <a>Durata: {{ l.durata }}<br></a>
            <a>Attore: {{ l.attore }}<br></a>
            <a>Categoria: {{ l.categoria }}<br></a>
            <a>Valutazione: {{ l.media_valutazione }}<br></a>
            <a>Trama: {{ l.sinossi }}<br><br></a>
            {%  if user.is_authenticated and l.id in listaspettacoli %}

                             <a class="button-62"  href="http://127.0.0.1:8000/gestione/homesala/{{ l.id }}" role="button">Prenotazione</a><br>
                             <hr color="black" align=”left” size=”1″ width=”300″  noshade>
            {% else %}
                            <a class="button-62"  onclick="motiva()" role="button">Film non disponibile</a><br>
                             <hr color="black" align=”left” size=”1″ width=”300″  noshade>
            {% endif %}
        </ul>
        </div1>
    {% endfor %}
    </body>
        <script>
        function motiva(){
            alert("non Loggato o film ancora non presente in sala")
        }
        function Controlla(film) {
                window.location.replace("http://127.0.0.1:8000/gestione/homesala/"+film)
        }
        </script>
{% endblock %}

Django/escinema/cinema/gestione/templates/gestione/pren.html
{% extends 'base.html' %}

{% block title %} {{view.title}} {% endblock  %}

{% load crispy_forms_tags %}
{% crispy form form.helper %}

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> 

{% block header1 %}
    <center>
        <h1>Prenota Spettacolo</h1>
    <p>Prenota qui il tuo spettacolo</p>
        {%  if user.is_authenticated  %}
    <a class="btn" href="{% url "home" %}" role="button">Home</a>
        {% else %}
         <a class="btn" href="{% url "home" %}" role="button">Home</a>
        <a class="btn"  href="{%  url 'login' %}" role="button">Login</a>
    {% endif %}
    {% for message in messages %}
        <p style="text-align:center;">{{message}}</p>
    {% endfor %}
    </center>

{% endblock  %}

{% block content %}
    
    <br>
    <div class="d-flex justify-content-center">
    <ul>
        <img src='{{ sala.film.immagine.url }}'  height="280" width="240"/><br>
        <label style="margin-top:20px" type="submit" name="output" value="{{ sala }}">{{ sala }}</label>
       {%  crispy form %}
    </ul>
    </div>
    <br>
    
{% endblock  %}

Django/escinema/cinema/gestione/templates/gestione/recensioni.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% crispy form form.helper %}

{% block header1 %}
  <h1>Home di {{user.username}} </h1>
  <p>Recensione Film
  </p>
<a class="btn" href="{% url "home" %}" role="button">Home</a>
{% endblock %}


{% block content %}
<div style="margin:auto;color:white;">
  <form class="well form-horizontal" action=" " method="post" enctype="multipart/form-data" id="contact_form">
    {% csrf_token %}
    {{ form | crispy }}
    <input class="button-62" style="margin-top:20px" type="submit" name="Submit" value="Crea">
  </form>
</div>
</div><!-- /.container -->
{% endblock %}